# Generated by Django 3.2 on 2021-04-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210318_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='attachment',
            order_with_respect_to='film',
        ),
    ]
